name: new-project
functions:
- url: https://raw.githubusercontent.com/mlrun/functions/master/serving/xgboost/xgb_serving.ipynb
  name: serving
- name: tstfunc
  spec:
    kind: job
    metadata:
      name: tstfunc
      project: new-project
    spec:
      command: handler.py
      args: []
      image: ''
      volumes: []
      volume_mounts: []
      env: []
      description: ''
      build:
        source: ./
        base_image: mlrun/mlrun:dev
        commands: []
        code_origin: '#2caf0393b582f68261d290de3f9f8a521aa5edb7'
workflows:
  main: workflow.py
