name: new-project
functions:
- url: https://raw.githubusercontent.com/mlrun/functions/master/serving/xgboost/xgb_serving.ipynb
  name: serving
- name: tstfunc
  spec:
    kind: job
    metadata:
      name: tstfunc
      project: new-project
    spec:
      command: handler.py
      args: []
      image: ''
      env: []
      description: ''
      build:
        source: ./
        base_image: mlrun/mlrun
        commands: []
        code_origin: https://github.com/yaronha/mlp2.git#8d2e289ac3f6c31d253aea02ecb62aee08b7457e
workflows:
  main: workflow.py
