name: new-project
functions:
- url: https://raw.githubusercontent.com/mlrun/functions/master/serving/xgboost/xgb_serving.ipynb
  name: serving
- name: tstfunc
  spec:
    kind: job
    metadata:
      name: tstfunc
      project: new-project
    spec:
      command: handler.py
      args: []
      image: ''
      env: []
      description: ''
      build:
        source: ./
        base_image: mlrun/mlrun
        commands: []
        code_origin: https://github.com/yaronha/mlp2.git#bc4adced86588da3354d5d5d2cc5feece83d8310
workflows:
- name: main
  code: workflow.py
